/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList <Integer> arr, int e){
        boolean result = false;

        if(arr == null)
            return false;
        for (Integer integer : arr) {
            if(integer.equals(e))
                result = true;
        }
        return result;

    }
}
